import Loader from "@/components/Loader";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Signin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ClerkLoading>
        <Loader />
      </ClerkLoading>
      <ClerkLoaded>
        <main className=" flex items-center justify-center  p-3">
          {children}
        </main>
      </ClerkLoaded>
    </ClerkProvider>
  );
}
